###
 # ca/x509/etc/ca-intermediate-name-constraints.conf - CA name
 # constraints
 #
 # These are specific name constraints for Example Inc. intermediate CA
 # certificates.  These add to the @c nameConstraints options to the
 # other extensions defined in @ca-root.conf.
 #
 # @copyright copyright 2025 Quoin Inc.
 ##


###
 # CA Intermediate PIV certificate extensions - name constraints.
 ##
[ qi_ca_intermediate_piv_extensions ]
  nameConstraints = \
    "critical", \
    permitted;email:"example.com"

###
 # CA Intermediate PIV server extensions - name constraints.
 ##
[ qi_ca_intermediate_server_extensions ]
  nameConstraints = \
    "critical", \
    permitted;DNS:"example.com", \
    permitted;DNS:".example.com", \
    permitted;DNS:"example.io", \
    permitted;DNS:".example.io"
