###
 # ca/x509/etc/default.conf - common default section
 #
 # Global constants used by all configurations. This must be the first
 # include in all other configuration files
 #
 # This file is @em parameterized by the following variables that must
 # be defined prior to including this file.
 #
 # - qi_ca_chain_base : The name of the certificate chain. Must be
 #     lower case alphanumeric and hyphen characters. Examples are @c
 #     rsa and @c ecc. All certificates under this chain must use the
 #     same type of key.
 # - qi_ca_name_base : The name of certificate authority. Must be
 #     lower case alphanumeric and hyphen characters. Examples are @c
 #     root, @c intermediate-piv, and @c intermediate-server.
 #
 # @see https://docs.openssl.org/master/man5/config/#settings
 # @copyright copyright 2025 Quoin Inc.
 ##


[ default ]
  ###
   # Allow relative paths in includes.
   #
   # @default 'abspath:false'
   ##
  .pragma 'abspath:false'

  ###
   # Dollar sign character, $, indicates a variable name.
   #
   # This means paths cannot contain the '$' character. Our convention
   # is to only allow lower ascii-alpha, numeric, and ascii '-'.
   #
   # @default 'dollarid:false'
   ##
  .pragma 'dollarid:false'

  ###
   # Enable diagnostics.
   #
   # @default '0'
   ##
  config_diagnostics = '1'

  ###
   # Module initialization section.
   #
   # @default-convention 'openssl_init'
   ##
  openssl_conf = 'qi_openssl_init'


  ###
   # CA root name.
   ##
  qi_ca_name = ${qi_ca_name_prefix}-${qi_ca_chain_base}-${qi_ca_name_base}

  ###
   # CA base directory.
   ##
  qi_ca_base_dir = ${qi_pki_base_dir}${qi_ca_chain_base}/${qi_ca_name_base}/

  ###
   # Certificate encrypted private key file.
   ##
  private_key = ${qi_ca_base_dir}ca.p8e

  ###
   # Certificate file.
   ##
  certificate = ${qi_ca_base_dir}ca.crt

  ###
   # Certificate serial number generated randomly.
   #
   # @default $dir/serial
   ##
  rand_serial = 'true'

  ###
   # Certificate serial number file.
   #
   # This is no longer used since a random serial number is
   # always used.
   #
   # @see rand_serial
   # @default $dir/serial
   ##
  serial = ""

  ###
   # CRL serial number file.
   #
   # @default $dir/crlnumber
   ##
 crlnumber = ${qi_ca_base_dir}db/crl.srl

  ###
   # Certificate index database.
   #
   # @default-convention 'index.txt'
   ##
  database = ${qi_ca_base_dir}db/index.txt

  ###
   # Certificate archive.
   #
   # @default-convention 'newcerts'
   ##
  new_certs_dir = ${qi_ca_base_dir}db/cert/


  ###
   # CA root Authority Information Access (AIA) certificate URL.
   #
   # @note Key expansion does not work in quoted values in this for
   #   this key in the info sections below.
   ##
  qi_ca_crt_url = ${qi_pki_base_url}${qi_ca_name}.crt

  ###
   # CA root CRL distribution point URL.
   #
   # @note Key expansion does not work in quoted values in this for
   #   this key in the info sections below.
   ##
  qi_ca_crl_url = ${qi_pki_base_url}${qi_ca_name}.crl


###
 # Defines how various OpenSSL modules and features should be
 # configured and loaded.
 #
 # The custom policy OIDs need to specified here.
 ##
[ qi_openssl_init ]
  ###
   # Specifies the section containing extra object identifiers.
   ##
  oid_section = 'qi_pki_pen_oids'
