###
 # Distinguished Name (DN) fields.
 #
 # @note zlint will issue the error @c e_subj_orgunit_in_ca_cert if
 #   the field @c organizationalUnitName is included in CA
 #   certificates.
 #
 # @copyright copyright 2025 Quoin Inc.
 ##
[ qi_req_distinguished_name ]
  countryName = 'US'
  stateOrProvinceName = 'NC'
  localityName = 'DAVIDSON'
  postalCode = '28036-8655'
  0.streetAddress = 'Hub @ Davidson'
  1.streetAddress = '210 MAIN ST'
  organizationName = 'Example Inc.'
