[ default ]
  ###
   # PKI base directory.
   ##
  qi_pki_base_dir = 'src/com/example/credential/ca/x509/'

  ###
   # PKI base URL.
   #
   # This is the base URL to retrieve CA issuing certificates and
   # certificate revokation lists.
   #
   # @note Use of the @c https instead of @c http diverges from CABF
   #   guidelines and will result in a @c zlint warning. All the tools
   #   and use cases work for Example work with @c https so we default
   #   to the safe protocol. This includes the following warnings:
   #
   #   - w_distribution_point_missing_ldap_or_uri
   #   - w_ext_aia_access_location_missing
   ##
  qi_pki_base_url = 'http://pki.example.com/'

  ###
   # CA root name.
   ##
  qi_ca_name_prefix = 'qi-ca-x509'
