###
 # etc/conf.d/req.conf - common CSR configuration section
 #
 # These are options in common to all certificate signing request
 # (CSR) configurations.
 #
 # We intentionally do not specify the following options:
 #
 # - @c req_extensions Section for CSR extensions. Default is
 #   undefined. The use of @c copy_extensions="none" in the @c [ca]
 #   section renders @req_extensions ineffective.
 # - All directives related to key generation. Instead, we generate a
 #   key prior to generating the CSR and then use the @c -key command
 #   line option for the @c openssl-req utility.
 #
 # @copyright copyright 2025 Quoin Inc.
 ##

[ req ]
  ###
   # Field values are UTF-8 strings.
   #
   # @default "false"
   ##
  utf8 = "true"

  ###
   # Emit UTF-8 strings when displaying.
   #
   # @default "utf8only"
   ##
  string_mask = "utf8only"

  ###
   # Disable prompting for DN fields.
   #
   # @note that boolean values "true" and "false" are not valid.
   #
   # @default "yes"
   ##
  prompt = "no"

  ###
   # Section for request Distinguished Name (DN) fields.
   #
   # @default-convention "req_distinguished_name"
   ##
  distinguished_name = "qi_req_distinguished_name"

  ###
   # Section for request extensions.
   #
   # @default <undefined>
   ##
  req_extensions = "qi_req_extensions"
