###
 # ca/x509/rsa/root/etc/ca.conf - Example PKI CA X.509 RSA Root
 #   Configuration
 #
 # This generates the root certificate for the RSA chain.
 #
 # @copyright copyright 2025 Quoin Inc.
 ##


[ default ]
  ###
   # CA chain name.
   #
   # @warning Must be before includes.
   ##
  qi_ca_chain_base = 'rsa'

  ###
   # CA root name.
   #
   # @warning Must be before includes.
   ##
  qi_ca_name_base = 'root'


.include 'src/com/example/credential/ca/x509/etc/pki.conf'
.include 'src/com/example/credential/ca/x509/etc/dn.conf'
.include 'src/com/example/credential/ca/x509/etc/pen.conf'
.include 'src/com/example/credential/ca/x509/etc/default.conf'
.include 'src/com/example/credential/ca/x509/etc/req.conf'
.include 'src/com/example/credential/ca/x509/etc/ca.conf'
.include 'src/com/example/credential/ca/x509/etc/ca-root.conf'
.include 'src/com/example/credential/ca/x509/etc/ca-intermediate-name-constraints.conf'


[ req ]
  ###
   # Specify section for self signed CA certificate extensions.
   ##
  x509_extensions = "qi_ca_extensions"


[ qi_req_distinguished_name ]
  commonName = "Example Inc. CA X.509 RSA Root 1"
